export const COMMON_HOBBIES = [
  "Reading",
  "Gaming",
  "Sports",
  "Music",
  "Cooking",
  "Baking",
  "Photography",
  "Drawing",
  "Painting",
  "Writing",
  "Yoga",
  "Running",
  "Cycling",
  "Swimming",
  "Hiking",
  "Traveling",
  "Dancing",
  "Singing",
  "Movies",
  "TV Shows",
  "Anime",
  "Board Games",
  "Card Games",
  "Gardening",
  "Crafts",
  "Knitting",
  "Fashion",
  "Makeup",
  "Coding",
  "Tech",
  "Volunteering",
  "Chess",
  "Meditation",
  "Gym",
  "Basketball",
  "Football",
  "Soccer",
  "Tennis",
  "Badminton",
  "Fishing",
  "Camping",
];

export const COMMON_MAJORS = [
  "Accounting",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African Studies",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agriculture",
  "Agronomy",
  "Air Traffic Management",
  "American Studies",
  "Anatomy",
  "Animation",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Applied Statistics",
  "Aquaculture",
  "Arabic Studies",
  "Archaeology",
  "Architecture",
  "Art History",
  "Artificial Intelligence",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Aviation",
  "Banking",
  "Behavioral Science",
  "Biochemistry",
  "Bioengineering",
  "Bioinformatics",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Biotechnology",
  "Botany",
  "Business Administration",
  "Business Analytics",
  "Business Information Systems",
  "Chemical Engineering",
  "Chemistry",
  "Child Development",
  "Chinese Studies",
  "Civil Engineering",
  "Classical Studies",
  "Cloud Computing",
  "Cognitive Science",
  "Communication",
  "Communication Engineering",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Criminal Justice",
  "Criminology",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dentistry",
  "Design",
  "Digital Marketing",
  "Economics",
  "Education",
  "Educational Psychology",
  "Educational Technology",
  "Electrical Engineering",
  "Electronic Engineering",
  "Energy Engineering",
  "Engineering Management",
  "English Literature",
  "English Studies",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Esports Management",
  "European Studies",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "Forestry",
  "French Studies",
  "Game Development",
  "Gender Studies",
  "Genetics",
  "Geography",
  "Geology",
  "Geophysics",
  "German Studies",
  "Graphic Design",
  "Health Administration",
  "Health Informatics",
  "History",
  "Hospitality Management",
  "Human Resource Management",
  "Humanities",
  "Human-Computer Interaction",
  "Industrial Design",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Law",
  "International Relations",
  "Islamic Studies",
  "Italian Studies",
  "Japanese Studies",
  "Journalism",
  "Law",
  "Landscape Architecture",
  "Latin American Studies",
  "Linguistics",
  "Logistics",
  "Management",
  "Manufacturing Engineering",
  "Marine Biology",
  "Marine Engineering",
  "Marketing",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medical Laboratory Science",
  "Medicine",
  "Mechatronics Engineering",
  "Microbiology",
  "Military Science",
  "Mining Engineering",
  "Mobile App Development",
  "Molecular Biology",
  "Music",
  "Nanotechnology",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Oceanography",
  "Optometry",
  "Organizational Psychology",
  "Petroleum Engineering",
  "Pharmacy",
  "Philosophy",
  "Photography",
  "Physical Education",
  "Physics",
  "Physiology",
  "Physiotherapy",
  "Political Science",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Psychology",
  "Quantum Computing",
  "Radiology",
  "Real Estate",
  "Religious Studies",
  "Renewable Energy Engineering",
  "Robotics",
  "Russian Studies",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Sound Engineering",
  "Spanish Studies",
  "Sports Science",
  "Statistics",
  "Structural Engineering",
  "Supply Chain Management",
  "Sustainable Development",
  "Systems Engineering",
  "Telecommunications Engineering",
  "Theatre",
  "Tourism Management",
  "Translation Studies",
  "Urban Design",
  "Urban Planning",
  "UX/UI Design",
  "Veterinary Medicine",
  "Video Production",
  "Visual Arts",
  "Web Development",
  "Womens Studies",
  "Zoology",
];

// Listings pagination + filters
export const PAGE_SIZE = 10;

export const ROOM_TYPES = [
  "single",
  "shared",
  "studio",
  "entire_apartment",
] as const;

export const GENDER_PREFERENCES = [
  "male_only",
  "female_only",
  "mixed",
  "no_preference",
] as const;

export const MAX_PRICE_OPTIONS = [500, 750, 1000, 1500, 2000] as const;

export const PUBLIC_LISTINGS_QUERY_BASE = "public-listings-page";

export const PREFETCH_WIDTHS = [384, 640] as const;

export const EMPTY_FILTERS = {
  search: "",
  roomType: null,
  maxPrice: null,
  genderPreference: null,
};

export const YEAR_LABELS: Record<string, string> = {
  "1st_year": "1st Year",
  "2nd_year": "2nd Year",
  "3rd_year": "3rd Year",
  "4th_year": "4th Year",
  graduate: "Graduate",
};

// Compatibility label maps
export const SLEEP_LABELS: Record<string, string> = {
  early_bird: "Early Bird",
  night_owl: "Night Owl",
  flexible: "Flexible",
};

export const NOISE_LABELS: Record<string, string> = {
  quiet: "Quiet",
  moderate: "Moderate",
  social: "Social",
};

export const GUEST_LABELS: Record<string, string> = {
  rarely: "Rarely",
  sometimes: "Sometimes",
  often: "Often",
};
